#!/bin/bash

if [ $(id -u) -ne 0 ]; then
        echo "Run this script as root"
        exit 1
fi

while getopts ":t:" o; do
    case "${o}" in
        t)
            t=${OPTARG}
            ((s == A || t == MX || t == CNAME)) || exit 1
            ;;
    esac
done
echo $t
